# Generated by Django 3.0.4 on 2020-03-30 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organisation',
            field=models.ForeignKey(default='c749d4a5-3d70-4661-a2c7-da1899c09282', on_delete=django.db.models.deletion.CASCADE, related_name='users', to='restapi.Organisation'),
        ),
    ]
