# Generated by Django 3.0.4 on 2020-04-01 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_user_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='hostname',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
