# Generated by Django 3.0.4 on 2020-04-01 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0003_machine_hostname'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='type',
            field=models.CharField(choices=[('node', 'node'), ('master', 'master')], default='node', max_length=6),
        ),
    ]
