# Generated by Django 3.0.4 on 2020-04-01 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0004_machine_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='trusted_admin',
        ),
        migrations.AlterField(
            model_name='machine',
            name='type',
            field=models.CharField(choices=[('node', 'node'), ('master', 'master'), ('admin', 'admin')], default='node', max_length=6),
        ),
    ]
